name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b41a50e50140652636c06bb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@0b7d39141e71f2861bf47964500255d3df0b5edc
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db596a1aedd2342c2b12a08c4818ed30f564bf
